#!/bin/bash
case_name=$1
case_kpi=$2
sd1=$3
sd2=$4
media_file=$5

echo "[ CASE NAME : $case_name KPI: $case_kpi START Self-define 1: $sd1  Self-define 2: $sd2 ]"
echo "********************************Need to sleep 120 sec************************************"
sleep 120
