#!/bin/bash
case_name=$1
case_kpi=$2
sd1=$3
sd2=$4
media_file=$5

echo "[ CASE NAME : $case_name KPI: $case_kpi START Self-define 1: $sd1  Self-define 2: $sd2 ]"

echo "Need to sleep 120 seconds"
sleep 120

cd cases_scripts
./dumpsys.sh $case_name &
cd -

if [ "$sd1" == "CHROME" ];then
echo "START CHROME BROWSER"
adb shell am start -a android.intent.action.VIEW -n com.android.chrome/.Main -d http://10.0.0.2/http/h264-720p.html

#adb shell am start -a android.intent.action.VIEW -n com.example.chromium/com.google.android.apps.chrome.Main -d http://10.0.0.2/http/h264-720p.html
elif [ "$sd1" == "STOCK" ];then
echo "START STOCK BROWSER"
adb shell am start -a android.intent.action.VIEW -n com.android.browser/.BrowserActivity -d http://10.0.0.2/http/h264-720p.html
fi


#Playing by enter the url
adb shell input tap 60 90
adb wait-for-device
adb shell input tap 60 90
adb wait-for-device
adb shell input tap 60 90
adb wait-for-device

#tap to play
adb shell input tap 500 300
adb wait-for-device
adb shell input tap 500 300
adb wait-for-device
adb shell input tap 500 300
echo "[ INPUT TAP 500 300 ]"

echo "Wait 5 seconds to play stream video"
sleep 5
