#!/bin/bash
case_name=$1
case_kpi=$2
sd1=$3
sd2=$4

echo "[ CASE NAME : $case_name KPI: $case_kpi STOP Self-define 1: $sd1  Self-define 2: $sd2 ]"

adb shell input keyevent 4
adb wait-for-device
adb shell input keyevent 3
echo "VIDEO PLAYBACK COMMON STOP"
cd cases_scripts
./video_playback_common_setup
cd -
