#!/bin/bash
case_name=$1
case_kpi=$2
sd1=$3
sd2=$4
media_file=$5

echo "[ CASE NAME : $case_name KPI: $case_kpi START Self-define 1: $sd1  Self-define 2: $sd2 ]"
echo "[ Media File: $media_file ]"

echo "Need to sleep 10 seconds \n"
read dtime 

echo "VIDEO PLAYBACK COMMON START"
cd cases_scripts
./video_playback_common_start ${case_name}_$case_kpi $media_file
cd -
