#!/bin/sh
adb wait-for-device
SERIAL=`adb get-serialno`

echo "[#### WIFI ON STARTING ####]"

echo "adb push wifi/$SERIAL/disconnect /data/misc/wifi/"
adb push wifi/$SERIAL/disconnect /data/misc/wifi/
echo "adb shell svc wifi disable"
adb wait-for-device
#adb shell svc wifi disable


echo "adb push wifi/$SERIAL/connect/wpa_supplicant.conf /data/misc/wifi/"
#adb push wifi/$SERIAL/connect /data/misc/wifi/
adb push wifi/$SERIAL/connect/wpa_supplicant.conf /data/misc/wifi/wpa_supplicant.conf

#echo "adb push wifi/$SERIAL/wpa_supplicant.conf.connected /data/misc/wifi/wpa_supplicant.conf"
#adb push wifi/$SERIAL/wpa_supplicant.conf.connected /data/misc/wifi/wpa_supplicant.conf
#sleep 2
#adb shell chown system:wifi /data/misc/wifi/wpa_supplicant.conf
#sleep 2
#
#echo "adb push wifi/$SERIAL/p2p_supplicant.conf.connected /data/misc/wifi/p2p_supplicant.conf"
#adb push wifi/$SERIAL/p2p_supplicant.conf.connected /data/misc/wifi/p2p_supplicant.conf
#sleep 2
#adb shell chown system:wifi /data/misc/wifi/p2p_supplicant.conf
#sleep 2

echo "adb shell svc wifi enable"
adb wait-for-device
adb shell svc wifi enable
echo "[#### WIFI ON STARTED ####]"

echo "SET IP ADDRESS 10.0.0.3"
adb shell busybox ifconfig wlan0 10.0.0.3
sleep 3
echo "IP ADDRESS of wlan0"
echo " ========================================= "
adb shell busybox ifconfig wlan0

echo "Wait seconds to connect the wifi"
sleep 5
